trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# RESTORE (IMPORTANT: point to API project)
- script: dotnet restore Backend/POS.API/POS.API.csproj
  displayName: Restore

# BUILD
- script: dotnet build Backend/POS.API/POS.API.csproj --configuration $(buildConfiguration)
  displayName: Build

# PUBLISH
- script: dotnet publish Backend/POS.API/POS.API.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Publish

- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop